spring.application.name=sistema-canchas

# Si no se define la variable SPRING_PROFILES_ACTIVE, por defecto sera 'dev' (tu local)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Configuracion de Base de Datos para Produccion (Render)
# Spring tomara los valores de las variables de entorno que nos dara Render
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Estrategia de JPA para Produccion
# En produccion usamos 'update' o 'none' para NO borrar los datos
# cada vez que se reinicie el servidor
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Tu Clave Secreta de JWT desde variable de entorno
application.security.jwt.secret-key=${JWT_SECRET_KEY}